# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "uas" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-c82ea056-e8c4-46f7-9a70-856f3aaa70bd";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-c82ea056-e8c4-46f7-9a70-856f3aaa70bd".device = "/dev/disk/by-uuid/c82ea056-e8c4-46f7-9a70-856f3aaa70bd";

  boot.initrd.luks.devices."luks-swap" = {
   device = "/dev/disk/by-uuid/5e693009-7cca-47e4-a3a6-94c5745513e5";
  };
  
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/00F9-9E4B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-swap"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
