# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "uas" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-5a01a6cd-d821-4a5a-9bf9-a04ac56e17ef";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-5a01a6cd-d821-4a5a-9bf9-a04ac56e17ef".device = "/dev/disk/by-uuid/5a01a6cd-d821-4a5a-9bf9-a04ac56e17ef";

  boot.initrd.luks.devices."luks-swap" = {
   device = "/dev/disk/by-uuid/6a0bb5a8-6a1b-4080-ba34-3cb40f2c5313";
  };


  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0A49-D2E7";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-swap"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
